# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\39102\Desktop\Guo\123\fengkong\Worker\ui_folder\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class uiWidgetWindow(object):
    def setupUi(self, Dialog, index=0):
        Dialog.setObjectName("Dialog")
        Dialog.setGeometry(QtCore.QRect(index * 80, index * 200, 500, 700))
        self.centralwidget = QtWidgets.QWidget(Dialog)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        # self.pushButton.setGeometry(QtCore.QRect(0, 690, 631, 41))
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.horizontalHeader().setStyleSheet("QHeaderView::section{background:skyblue;color: black;}")
        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        # self.tableWidget.setGeometry(QtCore.QRect(0, 0, 631, 681))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.verticalLayout.addWidget(self.pushButton)
        Dialog.setCentralWidget(self.centralwidget)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "详情"))
        self.pushButton.setText(_translate("Dialog", "Detial"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "交易员"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "盈亏"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "止损线"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "成交量"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "状态"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "持仓市值"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = uiWidgetWindow()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
